version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
  
jobs:
  build: 
    working_directory: ~/demo-circleci
    docker: 
      - image: "circleci/node:14.18.2-bullseye-browsers-legacy"
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - sonarcloud/scan
  test:
    working_directory: ~/demo-circleci
    docker:
      - image: "circleci/node:14.18.2-bullseye-browsers-legacy"
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage
      - store_artifacts:
          path: coverage
      - sonarcloud/scan

workflows:
  api_test:
    jobs:
      - build:
          context: SonarCloud
      - test: 
          context: SonarCloud
          requires:
            - build